<?php

/**
 *  @file media_vimeo/media_vimeo.module
 *
 *  Media: Vimeo provides a stream wrapper and formatters for videos provided
 *  by Vimeo, available at http://vimeo.com/.
 *
 *  @TODO:
 *  Tie in Vimeo API.
 *  Allow editors to search for videos to display on the browser.
 *  Allow editors to put in a vimeo username to display on the browser.
 *  Allow editors to log in w/ their credentials.
 *  Allow editors to upload videos to Vimeo.
 */

// A registry of variable_get defaults.
include_once('includes/media_vimeo.variables.inc');

/**
 *  Create stream wrapper for Vimeo videos.
 */
function media_vimeo_stream_wrappers() {
  return array(
    'vimeo' => array(
      'name' => t('Vimeo videos'),
      'class' => 'MediaVimeoStreamWrapper',
      'description' => t('Videos provided by Vimeo.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

function media_vimeo_media_format_form_prepare_alter(&$form, &$form_state, $media) {
  $settings = array('autosubmit' => ($media->type == "video"));
  drupal_add_js(array('media_format_form' => $settings), 'setting');
}

/**
 *  Implements hook_theme().
 */
function media_vimeo_theme($existing, $type, $theme, $path) {
  return array(
    'media_vimeo_preview_style' => array(
      'variables' => array('style_name' => NULL),
      'file' => 'media_vimeo.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_vimeo_field_formatter_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
      'file' => 'media_vimeo.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_vimeo_video' => array(
      'variables' => array('uri' => NULL, 'width' => NULL, 'height' => NULL, 'autoplay' => NULL, 'fullscreen' => NULL),
      'file' => 'media_vimeo.theme.inc',
      'path' => $path . '/includes/themes',
      'template' => 'media-vimeo-video',
    ),
    'media_vimeo_embed' => array(
      'variables' => array('style_name' => NULL, 'uri' => NULL, 'alt' => NULL, 'title' => NULL),
      'file' => 'media_vimeo.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_vimeo_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
      'file' => 'media_vimeo.theme.inc',
      'path' => $path . '/includes/themes',
    ),
  );
}

/**
 * Implementation of Styles module hook_styles_register().
 */
function media_vimeo_styles_register() {
  return array(
    'MediaVimeoStyles' => array(
      'field_types' => 'file',
      'name' => t('MediaVimeo'),
      'description' => t('Media Vimeo styles.'),
      'path' => drupal_get_path('module', 'media_vimeo') .'/includes',
      'file' => 'media_vimeo.styles.inc',
    ),
  );
}

/**
 *  Implements hook_styles_containers(). (Deprecated in version 2)
 */
function media_vimeo_styles_containers() {
  return array(
    'file' => array(
      'containers' => array(
        'media_vimeo' => array(
          'label' => t('Vimeo Styles'),
          'data' => array(
            'streams' => array(
              'vimeo',
            ),
            'mimetypes' => array(
              'video/vimeo',
            ),
          ),
          'weight' => 0,
          'filter callback' => 'media_vimeo_formatter_filter',
          'themes' => array(
            'field_formatter_styles' => 'media_vimeo_field_formatter_styles',
            'styles' => 'media_vimeo_styles',
            'preview' => 'media_vimeo_preview_style',
          ),
          'description' => t('Vimeo Styles will display embedded Vimeo videos and thumbnails to your choosing, such as by resizing, setting colors, and autoplay. You can !manage.', array('!manage' => l(t('manage your Vimeo styles here'), 'admin/config/media/media-vimeo-styles'))),
        ),
      ),
    ),
  );
}

function media_vimeo_formatter_filter($variables) {
  if (isset($variables['object'])) {
    $object = $variables['object'];
    return (file_uri_scheme($object->uri) == 'vimeo') && ($object->filemime == 'video/vimeo');
  }
}

/**
 * Implementation of the File Styles module's hook_file_styles_filter().
 */
function media_vimeo_file_styles_filter($object) {
  if ((file_uri_scheme($object->uri) == 'vimeo') && ($object->filemime == 'video/vimeo')) {
    return 'media_vimeo';
  }
}

/**
 *  Implements hook_styles_styles().
 */
function media_vimeo_styles_styles() {
  $styles = array(
    'file' => array(
      'containers' => array(
        'media_vimeo' => array(
          'styles' => array(
            'vimeo_thumbnail' => array(
              'name' => 'vimeo_thumbnail',
              'effects' => array(
                array('label' => t('Thumbnail'), 'name' => 'thumbnail', 'data' => array('thumbnail' => 1)),
                array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 100, 'height' => 75)),
              ),
            ),
            'vimeo_preview' => array(
              'name' => 'vimeo_preview',
              'effects' => array(
                array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 1)),
                array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 220, 'height' => 165)),
              ),
            ),
            'vimeo_full' => array(
              'name' => 'vimeo_full',
              'effects' => array(
                array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 0)),
                array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 640, 'height' => 480)),
                array('label' => t('Full screen'), 'name' => 'fullscreen', 'data' => array('fullscreen' => 1)),
              ),
            ),
          ),
        ),
      ),
    ),
  );

  // Allow any image style to be applied to the thumbnail.
  foreach (image_styles() as $style_name => $image_style) {
    $styles['file']['containers']['media_vimeo']['styles']['vimeo_thumbnail_' . $style_name] = array(
      'name' => 'vimeo_thumbnail_' . $style_name,
      'image_style' => $style_name,
      'effects' => array(
        array('label' => t('Thumbnail'), 'name' => 'thumbnail', 'data' => array('thumbnail' => 1)),
      ),
    );
  }

  return $styles;
}

/**
 *  Implements hook_styles_presets().
 */
function media_vimeo_styles_presets() {
  $presets = array(
    'file' => array(
      'square_thumbnail' => array(
        'media_vimeo' => array(
          'vimeo_thumbnail_square_thumbnail',
        ),
      ),
      'thumbnail' => array(
        'media_vimeo' => array(
          'vimeo_thumbnail',
        ),
      ),
      'small' => array(
        'media_vimeo' => array(
          'vimeo_preview',
        ),
      ),
      'large' => array(
        'media_vimeo' => array(
          'vimeo_full',
        ),
      ),
      'original' => array(
        'media_vimeo' => array(
          'vimeo_full',
        ),
      ),
    ),
  );
  return $presets;
}



/**
 *  Implements hook_media_parse().
 *
 *  @todo: this might be deprecated now that we have media_internet,
 *  but the hook is still being called in a couple places in media.
 */
function media_vimeo_media_parse($url, $options = array()) {
  $scheme = 'vimeo://';
  preg_match('@vimeo\.com/([^"\& ]+)@i', $url, $matches);
  if (isset($matches[1])) {
    return file_stream_wrapper_uri_normalize($scheme . 'v/' . $matches[1]);
  }
  // @TODO: Validate for malformed vimeo urls.
}

/**
 * Implements hook_media_internet_providers();
 */
function media_vimeo_media_internet_providers() {
  $path = drupal_get_path('module', 'media_vimeo');
  return array(
    'MediaInternetVimeoHandler' => array(
      'title' => 'vimeo',
      'image' => $path . '/images/stream-vimeo.png'
    ),
  );
}

class MediaInternetVimeoHandler extends MediaInternetBaseHandler {
  public function claim($embedCode) {
    if (media_vimeo_media_parse($embedCode)) {
      return TRUE;
    }
  }

  public function validate() {
    // @todo Media module currently fails when two files try to have the same
    //   URI, so catch that in the validation step. Some day, it would be nice
    //   to allow it, however. See http://drupal.org/node/952422.
    $uri = media_vimeo_media_parse($this->embedCode);
    $existing_files = file_load_multiple(array(), array('uri' => $uri));
    if (count($existing_files)) {
      throw new MediaInternetValidationException(t('You have entered a URL for a video that is already in your library.'));
    }
  }

  public function save() {
    $file = $this->getFileObject();
    file_save($file);
    return $file;
  }

  public function getFileObject() {
    $uri = media_vimeo_media_parse($this->embedCode);
    //@todo: this is terribly broken in some ways because the function is really
    // made for local files which are 'real'
    return file_uri_to_object($uri);
  }

  /**
   * Returns information about the media. See http://video.search.yahoo.com/mrss.
   *
   * @return
   *   If ATOM+MRSS information is available, a SimpleXML element containing
   *   ATOM and MRSS elements, as per those respective specifications.
   *
   * @todo Would be better for the return value to be an array rather than a
   *   SimpleXML element, but media_retrieve_xml() needs to be upgraded to
   *   handle namespaces first.
   */
  public function getMRSS() {
    $uri = media_vimeo_media_parse($this->embedCode);
    $video_id = arg(1, file_uri_target($uri));
    //@TODO: This is still the youtube format, Vimeo's fe
    $rss_url = url('http://gdata.vimeo.com/feeds/api/videos/' . $video_id, array('query' => array('v' => '2')));
    // @todo Use media_retrieve_xml() once it's upgraded to include elements
    //   from all namespaces, not just the document default namespace.
    $entry = simplexml_load_file($rss_url);
    return $entry;
  }

  /**
   * Returns information about the media. See http://www.oembed.com/.
   *
   * @return
   *   If oEmbed information is available, an array containing 'title', 'type',
   *   'url', and other information as specified by the oEmbed standard.
   *   Otherwise, NULL.
   */
  public function getOEmbed() {
    $uri = media_vimeo_media_parse($this->embedCode);
    $external_url = drupal_realpath($uri);
    $oembed_url = url('http://www.vimeo.com/oembed', array('query' => array('url' => $external_url, 'format' => 'json')));
    $response = drupal_http_request($oembed_url);
    if (!isset($response->error)) {
      return drupal_json_decode($response->data);
    }
  }
}
